_wandb:
    value:
        cli_version: 0.28.1
        e:
            r1fdpsaw51ruh1f4lpg69sn6ma8owohz:
                args:
                    - --data-dir
                    - /home/quinteroossa/captain_data/captain3data
                    - --run-name
                    - ppo_extrisk_only
                    - --wandb
                codePath: experiments/train_ppo.py
                codePathLocal: experiments/train_ppo.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "454457757696"
                        used: "45555511296"
                email: quinteroossa37@gmail.com
                executable: /home/quinteroossa/captain/.venv/bin/python3
                git:
                    commit: 4d7d8f56338e12b97f177e542e03bf389d3cc372
                    remote: git@github.com:quinteroossa/captain.git
                gpu: NVIDIA GeForce RTX 2080 Ti
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-dce4055d-f181-b00c-5b0c-202b27fd335c
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-baf02195-c234-2189-63ca-cd57d2555f99
                host: milk
                memory:
                    total: "33562529792"
                os: Linux-6.12.74+deb13+1-amd64-x86_64-with-glibc2.41
                program: /home/quinteroossa/captain/experiments/train_ppo.py
                python: CPython 3.13.5
                root: /home/quinteroossa/captain
                startedAt: "2026-07-21T11:45:27.676232Z"
                writerId: r1fdpsaw51ruh1f4lpg69sn6ma8owohz
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.5
            "5": 0.28.1
            "12": 0.28.1
            "13": linux-x86_64
activation:
    value: relu
avg_carrying_capacity:
    value: 100
cells_per_step:
    value: 50
clip_coef:
    value: 0.2
device:
    value: cuda
dispersal_rate:
    value: 0.5
dispersal_window:
    value: 3
ent_coef:
    value: 0.05
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
hidden_dim:
    value: 64
k:
    value: 50
lr:
    value: 0.0003
lr_anneal:
    value: true
max_grad_norm:
    value: 0.5
min_habitat_suitability:
    value: 0.05
minibatch_size:
    value: 32
n_epochs_per_update:
    value: 4
n_time_steps:
    value: 200
n_updates:
    value: 500
plot_train_freq:
    value: 50
rollout_steps:
    value: 128
seed:
    value: 42
subset:
    value: true
target_protected_cells:
    value: 17000
vf_coef:
    value: 0.5
